### importing the necesarry libraries ###

In [6]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression

### loading the data ###

In [7]:
#loading data
data=pd.read_csv("1.01 original.csv")

In [20]:
#initializing variables
x=data["SAT"].to_numpy()
y=data["GPA"].to_numpy()

In [24]:

x=x.reshape(-1,1)
reg=LinearRegression()
reg.fit(x,y)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [25]:
reg.score(x,y)

0.40600391479679765

In [26]:
reg.coef_

array([0.00165569])

In [27]:
reg.intercept_

0.2750402996602803

In [28]:
reg.predict([[1740]])


array([3.15593751])

In [14]:
new_score=pd.DataFrame({"new_SAT":[1740,1760]})
new_score

new_SAT
0     1740
1     1760

In [29]:
reg.predict(new_score)

array([3.15593751, 3.18905127])

In [30]:
new_score["new_GPA"]=reg.predict(new_score)
new_score

new_SAT   new_GPA
0     1740  3.155938
1     1760  3.189051